# Generated by Django 5.2 on 2025-05-08 10:13

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0401111111', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
