# Generated by Django 5.1.7 on 2025-04-06 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location_point_1', models.CharField(max_length=255)),
                ('location_point_2', models.CharField(max_length=255)),
                ('location_point_3', models.CharField(max_length=255)),
                ('location_point_4', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('area', models.FloatField(blank=True, null=True)),
                ('location_point_1', models.CharField(max_length=255)),
                ('location_point_2', models.CharField(max_length=255)),
                ('location_point_3', models.CharField(max_length=255)),
                ('location_point_4', models.CharField(max_length=255)),
                ('totalTrees', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='farm.farm')),
            ],
        ),
    ]
