# Generated by Django 5.2 on 2025-05-08 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.FloatField()),
                ('plant_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_points', to='farm.farm')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_entity', models.CharField(max_length=255)),
                ('confidence_level', models.CharField(max_length=50)),
                ('area_size', models.FloatField()),
                ('density_of_plant', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('property_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_suggestions', to='farm.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('confidence', models.CharField(max_length=50)),
                ('plant_per_section', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_entity', models.CharField(blank=True, max_length=255, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='farm.farm')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='farm.boundarypoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='farm.inspectionsuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('observation_status', models.CharField(default='Nil', max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('segment', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_level', models.CharField(blank=True, max_length=50, null=True)),
                ('target_entity', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_points', to='farm.farm')),
                ('inspection_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_points', to='farm.inspectionsuggestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='inspectionsuggestion',
            index=models.Index(fields=['property_location'], name='farm_inspec_propert_e28154_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionsuggestion',
            index=models.Index(fields=['user'], name='farm_inspec_user_id_1094df_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionsuggestion',
            index=models.Index(fields=['mobile_id'], name='farm_inspec_mobile__b470d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionsuggestion',
            index=models.Index(fields=['sync_status'], name='farm_inspec_sync_st_c1221e_idx'),
        ),
        migrations.AddIndex(
            model_name='observationpoint',
            index=models.Index(fields=['farm'], name='farm_observ_farm_id_f4bb55_idx'),
        ),
        migrations.AddIndex(
            model_name='observationpoint',
            index=models.Index(fields=['mobile_id'], name='farm_observ_mobile__00f5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='observationpoint',
            index=models.Index(fields=['sync_status'], name='farm_observ_sync_st_0923d1_idx'),
        ),
    ]
