# Generated by Django 5.2 on 2025-05-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionobservation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inspection_images/'),
        ),
        migrations.AddField(
            model_name='inspectionobservation',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
