# Generated by Django 5.2 on 2025-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_inspectionobservation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationpoint',
            name='image',
            field=models.ImageField(default='hello', upload_to='observation_images/'),
            preserve_default=False,
        ),
    ]
