# Generated by Django 5.1.7 on 2025-04-06 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scientificName', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('controlMeasures', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamplingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventDate', models.DateTimeField()),
                ('recommendations', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('blockDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_events', to='farm.block')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blockId', models.CharField(max_length=255)),
                ('plantId', models.CharField(max_length=255)),
                ('detectionResult', models.BooleanField()),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='surveillance.samplingevent')),
            ],
        ),
        migrations.CreateModel(
            name='SurveillancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designPrevalence', models.FloatField()),
                ('detectionConfidence', models.FloatField()),
                ('observerDetectionProb', models.FloatField()),
                ('sampleSize', models.IntegerField()),
                ('scheduleStart', models.DateTimeField()),
                ('scheduleFrequency', models.CharField(max_length=100)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('selectedBlockIds', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('blocks', models.ManyToManyField(related_name='plans', to='farm.block')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='farm.farm')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='surveillance.pest')),
            ],
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='surveillance.surveillanceplan'),
        ),
    ]
