# Generated by Django 5.1.7 on 2025-04-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillanceplan',
            name='sampleSize',
        ),
    ]
