# Generated by Django 5.1.7 on 2025-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_remove_surveillanceplan_samplesize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillanceplan',
            name='selectedBlockIds',
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='sampleSize',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
